version: "3.7"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    network_mode: "host"
  mz2mo:
    image: ${NCP_CONTAINER_REGISTRY}/mz2mo:${PROJECT_VERSION}
    container_name: mz2mo
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
