springdoc:
    packages-to-scan: com.mz2mo
    swagger-ui:
        path: /api-docs
        tags-sorter: method
    api-docs:
        path: /api-docs/json
        groups.enabled: true
    cache.disabled: true
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
api:
  version: "1.0.0"
