spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
      hibernate:
          ddl-auto: create-drop
