name: DEVELOP_TEST

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Gradle Build
      run: ./gradlew build

    - name: Run Test
      id: test
      run: ./gradlew test
